services:
  - type: web
    name: shopping-server
    runtime: node
    repo: https://github.com/Pravindevkar007/shopping-server.git
    branch: master
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
